### ISSUE TITLE
when I execute "fly deploy"，there is an error

### ISSUE THREAD

**Issue by wangyang814** [yoeven/ai-video-search-engine#2]
[root@iZrj9d4ppwccrjoi39i1kgZ ai-video-search-engine-main]# fly deploy
==> Verifying app config
Validating /root/ai-video-search-engine-main/fly.toml
Platform: machines
✓ Configuration is valid
--> Verified app config
==> Building image
Remote builder fly-builder-summer-moon-6958 ready
Remote builder fly-builder-summer-moon-6958 ready
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
[+] Building 44.9s (14/18)                                                                                                                                                 
 => [internal] load build definition from Dockerfile                                                                                                                  0.5s
 => => transferring dockerfile: 1.09kB                                                                                                                                0.5s
 => [internal] load .dockerignore                                                                                                                                     0.5s
 => => transferring context: 469B                                                                                                                                     0.5s
 => resolve image config for docker.io/docker/dockerfile:1                                                                                                            0.5s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:ac85f380a63b13dfcefa89046420e1781752bab202122f8f50032edf31be0021                                       0.0s
 => [internal] load build definition from Dockerfile                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/node:18.19.0-slim                                                                                                  0.4s
 => [internal] load .dockerignore                                                                                                                                     0.0s
 => [internal] load build context                                                                                                                                     0.9s
 => => transferring context: 344.37kB                                                                                                                                 0.9s
 => [base 1/3] FROM docker.io/library/node:18.19.0-slim@sha256:fe687021c06383a2bc5eafa6db29b627ed28a55f6bdfbcea108f0c624b783c37                                       0.0s
 => CACHED [base 2/3] WORKDIR /app                                                                                                                                    0.0s
 => CACHED [base 3/3] RUN npm install -g yarn@1.22.21 --force                                                                                                         0.0s
 => CACHED [build 1/6] RUN apt-get update -qq &&     apt-get install --no-install-recommends -y build-essential node-gyp pkg-config python-is-python3                 0.0s
 => CACHED [build 2/6] COPY --link package.json yarn.lock ./                                                                                                          0.0s
 => ERROR [build 3/6] RUN yarn install --frozen-lockfile --production=false                                                                                          42.5s
------                                                                                                                                                                     
 > [build 3/6] RUN yarn install --frozen-lockfile --production=false:                                                                                                      
#0 0.652 yarn install v1.22.21                                                                                                                                             
#0 0.736 [1/4] Resolving packages...                                                                                                                                       
#0 1.009 [2/4] Fetching packages...                                                                                                                                        
#0 30.30 warning replicate@0.22.0: The engine "git" appears to be invalid.                                                                                                 
#0 30.31 [3/4] Linking dependencies...
#0 30.31 warning "react-hot-toast > goober@2.1.13" has unmet peer dependency "csstype@^3.0.10".
#0 30.32 warning " > @graphql-codegen/typescript-react-apollo@4.1.0" has unmet peer dependency "graphql-tag@^2.0.0".
#0 30.34 warning Workspaces can only be enabled in private projects.
#0 30.35 warning Workspaces can only be enabled in private projects.
#0 30.35 warning Workspaces can only be enabled in private projects.
#0 30.39 warning Workspaces can only be enabled in private projects.
#0 38.50 [4/4] Building fresh packages...
#0 41.06 $ yarn codegen
#0 41.36 yarn run v1.22.21
#0 41.38 $ graphql-codegen --config codegen.ts
#0 42.15 [Error: ENOENT: no such file or directory, open '/app/codegen.ts'] {
#0 42.15   errno: -2,
#0 42.15   code: 'ENOENT',
#0 42.15   syscall: 'open',
#0 42.15   path: '/app/codegen.ts'
#0 42.15 }
#0 42.19 error Command failed with exit code 1.
#0 42.19 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#0 42.21 error Command failed with exit code 1.
#0 42.21 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
Error: failed to fetch an image or build from source: error building: failed to solve: executor failed running [/bin/sh -c yarn install --frozen-lockfile --production=false]: exit code: 1
[root@iZrj9d4ppwccrjoi39i1kgZ ai-video-search-engine-main]#

**Comment by yoeven** [comment]
Could you share more details on where you ran `fly deploy`. Seems like you also ran `yarn` which requires .env file info to work and a fly account set up

**Comment by wangyang814** [comment]
I did not configure the .env file, but configured the /admin/configs/fly.toml file

**Comment by wangyang814** [comment]
Another question, what files do I need to configure when deploying this project?

**Comment by yoeven** [comment]
.env file and fly.toml file, you'll need to create the relavant accounts to get the info for those files
