### ISSUE TITLE
Are there detailed deployment steps?

### ISSUE THREAD

**Issue by wangyang814** [yoeven/ai-video-search-engine#3]
![image](https://github.com/yoeven/ai-video-search-engine/assets/24220817/119db9e0-7ba0-4d45-bf8c-60c1f8de4d8f)

Besides these instructions, are there any more detailed deployment steps?

**Comment by yoeven** [comment]
Hi there aren't detailed steps right now but I'll try to create some when I can, alternatively you could write one and submit a PR as you're trying to set it up :)
